package errors

import stderrors "errors"

var (
	ErrEmailAlreadyRegistered = stderrors.New("email already registered")
	ErrFailedToCheckEmail     = stderrors.New("failed to check email")
	ErrFailedToHashPassword   = stderrors.New("failed to hash password")
	ErrFailedToCreateUser         = stderrors.New("failed to create user")
	ErrInvalidCredentials         = stderrors.New("invalid email or password")
	ErrFailedToGenerateAccessToken  = stderrors.New("failed to generate access token")
	ErrFailedToGenerateRefreshToken = stderrors.New("failed to generate refresh token")
	ErrUnsupportedGitProvider       = stderrors.New("unsupported git provider")
	ErrInvalidGitAccessToken        = stderrors.New("invalid git access token")
	ErrFailedToSaveGitIntegration   = stderrors.New("failed to save git integration")
	ErrInvalidBaseURL               = stderrors.New("invalid base url")
	ErrFailedToFetchGitProjects       = stderrors.New("failed to fetch git projects")
	ErrFailedToSaveGitProjects        = stderrors.New("failed to save git projects")
	ErrGitIntegrationNotFound         = stderrors.New("git integration not found")
	ErrGitProjectNotFound             = stderrors.New("one or more git projects not found")
	ErrFailedToListGitIntegrations    = stderrors.New("failed to list git integrations")
	ErrFailedToListGitProjects        = stderrors.New("failed to list git projects")
	ErrFailedToUpdateTrackedProjects  = stderrors.New("failed to update tracked projects")
	ErrFailedToSyncGitIntegration     = stderrors.New("failed to sync git integration")
	ErrFailedToSyncCommits            = stderrors.New("failed to sync commits")
	ErrInvalidReportDate              = stderrors.New("invalid report date")
	ErrNoTrackedGitProjects           = stderrors.New("no tracked git projects found")
	ErrFailedToFetchGitActivity       = stderrors.New("failed to fetch git activity")
	ErrFailedToGenerateDSR            = stderrors.New("failed to generate dsr")
	ErrFailedToSaveDSR                = stderrors.New("failed to save dsr")
	ErrDSRReportNotFound              = stderrors.New("dsr report not found")
	ErrFailedToListDSRReports         = stderrors.New("failed to list dsr reports")
	ErrInvalidLocalGitPath            = stderrors.New("invalid local git repository path")
	ErrFailedToSaveLocalGitRepository = stderrors.New("failed to save local git repository")
	ErrFailedToListLocalGitRepositories = stderrors.New("failed to list local git repositories")
	ErrLocalGitRepositoryNotFound     = stderrors.New("local git repository not found")
	ErrFailedToUpdateTrackedLocalRepos = stderrors.New("failed to update tracked local repositories")
	ErrFailedToDeleteLocalGitRepository = stderrors.New("failed to delete local git repository")
	ErrNoTrackedLocalGitRepositories  = stderrors.New("no tracked local git repositories found")
	ErrFailedToSyncLocalGitActivity   = stderrors.New("failed to sync local git activity")
	ErrUnsupportedPlanningProvider    = stderrors.New("unsupported planning provider")
	ErrInvalidPlanningCredentials     = stderrors.New("invalid planning tool credentials")
	ErrFailedToSavePlanningIntegration = stderrors.New("failed to save planning integration")
	ErrFailedToGetPlanningIntegration  = stderrors.New("failed to get planning integration")
	ErrFailedToListPlanningIntegrations = stderrors.New("failed to list planning integrations")
	ErrPlanningIntegrationNotFound    = stderrors.New("planning integration not found")
	ErrFailedToDeletePlanningIntegration = stderrors.New("failed to delete planning integration")
	ErrFailedToSyncPlanningActivity   = stderrors.New("failed to sync planning tool activity")
	ErrInvalidActiveRepository        = stderrors.New("invalid active repository")
	ErrFailedToSaveActiveRepository   = stderrors.New("failed to save active repository")
	ErrFailedToGetActiveRepository    = stderrors.New("failed to get active repository")
	ErrActiveRepositoryNotFound       = stderrors.New("active repository not found")
	ErrFailedToFetchActivity          = stderrors.New("failed to fetch activity")
)
